### ISSUE TITLE
Something is going wrong here

### ISSUE THREAD

**Issue by Chu127001** [Chu127001/bounty_1#1]
Comment here %%

**Comment by status-open-bounty** [comment]
Balance: 0.0002 ETH
Tokens: SNT: 0.00
Contract address: [0x400a848e50409fb2c315d7bf3792810b6e3b93ca](https://ropsten.etherscan.io/address/0x400a848e50409fb2c315d7bf3792810b6e3b93ca)
Network: Testnet (Ropsten)
Paid to: churik
