### ISSUE TITLE
Second Test

### ISSUE THREAD

**Issue by Chu127001** [Chu127001/bounty_1#5]
Second Test

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 20.00
Contract address: [0x781f72f5b4eea89d4ff2756e1de261b435a7e717](https://ropsten.etherscan.io/address/0x781f72f5b4eea89d4ff2756e1de261b435a7e717)
Network: Testnet (Ropsten)
Paid to: churik
